name: run-tests

on:
  push:
    branches: [2.x]
  pull_request:
    branches: [2.x]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.1, 8.0, 7.4]
        laravel: [10.*, 9.*, 8.*]
        stability: [prefer-lowest, prefer-stable]
        script: true
        include:
          - laravel: 10.*
            testbench: 8.*
            carbon: 2.*
          - laravel: 9.*
            testbench: 7.*
            carbon: 2.*
          - laravel: 8.*
            testbench: 6.*
            carbon: 2.*
            script: false
        exclude:
          - laravel: 8.*
            php: 8.1
          - laravel: 9.*
            php: 7.4
          - laravel: 10.*
            php: 7.4
          - laravel: 10.*
            php: 8.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Remove Laravel Pint
        if: "matrix.php < 8"
        run: |
          composer remove "laravel/pint" --dev --no-interaction --no-update

      - name: Setup dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update

      - name: Install depecencies
        if: ${{ (matrix.stability != 'prefer-lowest' && matrix.laravel <= 8) || matrix.laravel > 8 }}
        run: |
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction ${{ matrix.script ? '' : '--no-scripts' }}

      # - name: Install depecencies and run scripts
      #   if: ${{ (matrix.stability != 'prefer-lowest' && matrix.laravel <= 8) || matrix.laravel > 8 }}
      #   run: |
      #     composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      # - name: Install depecencies and dont run scripts
      #   if: ${{ matrix.stability == 'prefer-lowest' && matrix.laravel <= 8 }}
      #   run: |
      #     composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-scripts


      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        if: "matrix.laravel >= 8"
        run: vendor/bin/pest
